version: '3'
services:
  dev:
    image: node:8.1.3-alpine
    working_dir: /opt/app
    command: sh run-dev.sh
    environment:
      NODE_ENV: development
      PORT: 3000
      VIRTUAL_HOST: kqxs.dev
      VIRTUAL_PORT: 3000
      HTTPS_METHOD: noredirect # support both http and https
    ports:
      - "3000"
      - "5858"
    volumes:
      - .:/opt/app
    restart: unless-stopped
    # to get this work with https://github.com/jwilder/nginx-proxy
    # related: https://github.com/jwilder/nginx-proxy/issues/305
    network_mode: bridge
  db:
    image: mongo
    restart: unless-stopped
    network_mode: bridge